apiVersion: v1
kind: Pod
metadata:
  name: new-pod
  labels:
    app: myapp
spec: 
 containers :
  - name: my-container
    image: nginx:latest
    ports:
     - containerPort: 80  

---
apiVersion : v1
kind : service
metadata:
  name : cbz-svc 
  label : 
     app : cbz-app
     env : dev
  spec: 
    - ports:
      targetport: 80
      protocal: TCP 
  Type : NodePort 
  selector:
    app: cbz-app           